// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"music/service/mv/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/mv/all",
				Handler: MvAllHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mv/detail",
				Handler: MvDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mv/detail/info",
				Handler: MvDetailInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mv/exclusive/rcmd",
				Handler: MvExclusiveRcmdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mv/first",
				Handler: MvFirstHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mv/url",
				Handler: MvUrlHandler(serverCtx),
			},
		},
	)
}
