// Code generated by goctl. DO NOT EDIT.
package types

type CaptchaSentReq struct {
	Ctcode    int `form:"ctcode,default=86"`
	Cellphone int `form:"cellphone"`
}

type CaptchaSentReply struct {
	Code int  `json:"code"`
	Data bool `json:"data"`
}

type CaptchaVerifyReq struct {
	Ctcode    int `form:"ctcode,default=86"`
	Cellphone int `form:"cellphone"`
	Captcha   int `form:"captcha"`
}

type CaptchaVerifyReply struct {
	Code int  `json:"code"`
	Data bool `json:"data"`
}
