// Code generated by goctl. DO NOT EDIT.
package types

type SearchReq struct {
	Type     string `form:"type"`
	Keywords string `form:"keywords"`
	Scene    string `form:"scene"`
	Limit    string `form:"limit,default=30"`
	Offset   int    `form:"offset,default=0"`
}

type SearchReply struct {
	Result interface{} `json:"result"`
	Code   int         `json:"code"`
}

type SearchDefaultReq struct {
}

type SearchDefaultReply struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type SearchHotReq struct {
	Type int `form:"type,default=1111"`
}

type SearchHotReply struct {
	Code   int         `json:"code"`
	Result interface{} `json:"result"`
}

type SearchHotDetailReply struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type SearchMultimatchReq struct {
	Type int    `form:"type,default=1"`
	S    string `form:"s,default=''"`
}

type SearchMultimatchReply struct {
	Code int `json:"code"`
}

type SearchSuggestReq struct {
	Keywords string `form:"keywords,default=''"`
	Type     string `form:"type,optional"`
}

type SearchSuggestReply struct {
	Result interface{} `json:"result"`
	Code   int         `json:"code"`
}
