// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"music/service/artist/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/artist/list",
				Handler: ArtistListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/album",
				Handler: ArtistAlbumHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/desc",
				Handler: ArtistDescHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/detail",
				Handler: ArtistDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/fans",
				Handler: ArtistFansHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/follow/count",
				Handler: ArtistFollowCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/mv",
				Handler: ArtistMvHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/songs",
				Handler: ArtistSongsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/top/song",
				Handler: ArtistTopSongHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/artist/video",
				Handler: ArtistVideoHandler(serverCtx),
			},
		},
	)
}
