// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Email         string `form:"email"`
	Password      string `form:"password"`
	RememberLogin bool   `form:"rememberLogin,default=true"`
}

type LoginReply struct {
}

type LoginCellphoneReq struct {
	Phone         int    `form:"phone"`
	Countrycode   int    `form:"countrycode,default=86"`
	Captcha       string `form:"captcha,optional,omitempty"`
	Password      string `form:"password"`
	RememberLogin bool   `form:"rememberLogin,default=true"`
}

type LoginCellphoneReply struct {
	Code      int         `json:"code"`
	Message   string      `json:"message"`
	LoginType int         `json:"loginType"`
	Account   interface{} `json:"account"`
	Token     string      `json:"token"`
	Profile   interface{} `json:"profile"`
	Bindings  interface{} `json:"bindings"`
	Cookie    string      `json:"cookie"`
}

type LoginQrCheckReq struct {
	Key  string `form:"key"`
	Type int    `form:"type,default=1"`
}

type LoginQrCheckReply struct {
}

type LoginQrCreateReq struct {
	Key   string `form:"key"`
	Qrimg string `form:"qrimg,optional"`
}

type LoginQrCreateReply struct {
}

type LoginQrKeyReq struct {
	Type int `form:"type,default=1"`
}

type LoginQrKeyReply struct {
}

type LoginRefreshReq struct {
}

type LoginRefreshReply struct {
}

type LoginStatusReq struct {
}

type LoginStatusReply struct {
}
