// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"music/service/comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/comment",
				Handler: CommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/album",
				Handler: CommentAlbumHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/dj",
				Handler: CommentDjHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/event",
				Handler: CommentEventHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/floor",
				Handler: CommentFloorHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/hot",
				Handler: CommentHotHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/hug/list",
				Handler: CommentHugListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/like",
				Handler: CommentLikeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/music",
				Handler: CommentMusicHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/mv",
				Handler: CommentMvHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/new",
				Handler: CommentNewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/play/list",
				Handler: CommentPlayListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/video",
				Handler: CommentVideoHandler(serverCtx),
			},
		},
	)
}
