// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"music/service/playlist/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/playlist/catlist",
				Handler: PlaylistCatlistHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/create",
				Handler: PlaylistCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/delete",
				Handler: PlaylistDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/detail",
				Handler: PlaylistDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/detail/dynamIc",
				Handler: PlaylistDetailDynamIcHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/highquality/tags",
				Handler: PlaylistHighqualityTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/hot",
				Handler: PlaylistHotHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/mylike",
				Handler: PlaylistMylikeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/name/update",
				Handler: PlaylistNameUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/order/update",
				Handler: PlaylistOrderUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/subscribe",
				Handler: PlaylistSubscribeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/subscribers",
				Handler: PlaylistSubscribersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/tags/update",
				Handler: PlaylistTagsUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/track/add",
				Handler: PlaylistTrackAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/update/playcount",
				Handler: PlaylistUpdatePlaycountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/playlist/video/recent",
				Handler: PlaylistVideoRecentHandler(serverCtx),
			},
		},
	)
}
