// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"music/service/login/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/cellphone",
				Handler: LoginCellphoneHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/qr/check",
				Handler: LoginQrCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/qr/create",
				Handler: LoginQrCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/qr/key",
				Handler: LoginQrKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/refresh",
				Handler: LoginRefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/status",
				Handler: LoginStatusHandler(serverCtx),
			},
		},
	)
}
