// Code generated by goctl. DO NOT EDIT.
package types

type DjBannerReq struct {
}

type DjBannerReqly struct {
	Data interface{} `json:"data"`
	Code int         `json:"code"`
}

type DjCategoryExcludehotReq struct {
}

type DjCategoryExcludehotReqly struct {
	Data interface{} `json:"data"`
	Code int         `json:"code"`
}

type DjCategoryRecommendReq struct {
}

type DjCategoryRecommendReqly struct {
	Data interface{} `json:"data"`
	Code int         `json:"code"`
}

type DjCatelistReq struct {
}

type DjCatelistReply struct {
	Data interface{} `json:"data"`
	Code int         `json:"code"`
}

type DjDetailReq struct {
	Id int `form:"id"`
}

type DjDetailReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DjHotReq struct {
	Limit  int `form:"limit,default=30"`
	Offset int `form:"offset,default=0"`
}

type DjHotReply struct {
	DjRadios interface{} `json:"djRadios"`
	HasMore  bool        `json:"hasMore"`
	Code     int         `json:"code"`
}

type DjPaygiftReq struct {
	Limit  int `form:"limit,default=30"`
	Offset int `form:"offset,default=0"`
}

type DjPaygiftReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DjPersonalizeRecommendReq struct {
	Limit int `form:"limit,default=6"`
}

type DjPersonalizeRecommendReply struct {
	Code int         `json:"code"`
	Data interface{} `json:"data"`
}

type DjProgramReq struct {
	RadioId int  `form:"radioId"`
	Limit   int  `form:"limit,default=30"`
	Offset  int  `form:"offset,default=0"`
	Asc     bool `form:"asc,default=false"`
}

type DjProgramReply struct {
	Count    int         `json:"count"`
	Code     int         `json:"code"`
	Programs interface{} `json:"programs"`
	More     bool        `json:"more"`
}

type DjProgramDetailReq struct {
	Id int `form:"id"`
}

type DjProgramDetailReply struct {
	Program interface{} `json:"program"`
	Code    int         `json:"code"`
}

type DjProgramToplistReq struct {
	Limit  int `form:"limit,default=100"`
	Offset int `form:"offset,default=0"`
}

type DjProgramToplistReply struct {
	UpdateTime string      `json:"updateTime"`
	Toplist    interface{} `json:"toplist"`
	Code       int         `json:"code"`
}

type DjProgramToplistHoursReq struct {
	Limit int `form:"limit,default=100"`
}

type DjProgramToplistHoursReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DjRadioHotReq struct {
	CateId int `form:"cateId"`
	Limit  int `form:"limit,default=30"`
	Offset int `form:"offset,default=0"`
}

type DjRadioHotReply struct {
	DjRadios interface{} `json:"djRadios"`
	HasMore  bool        `json:"hasMore"`
	Count    int         `json:"count"`
	Code     int         `json:"code"`
}

type DjRecommendReq struct {
}

type DjRecommedReply struct {
	DjRadios interface{} `json:"djRadios"`
	Name     string      `json:"name"`
	Code     int         `json:"code"`
}

type DjRecommendTypeReq struct {
	CateId int `form:"cateId"`
}

type DjRecommendTypeReply struct {
	DjRadios interface{} `json:"djRadios"`
	HasMore  bool        `json:"hasMore"`
	Code     int         `json:"code"`
}

type DjSubReq struct {
	T  string `form:"t,options=sub,unsub"`
	Id int    `form:"id"`
}

type DjSubReply struct {
}

type DjSublistReq struct {
	Limit  int  `form:"limit,default=30"`
	Offset int  `form:"offset,default=0"`
	Total  bool `form:"total,default=true"`
}

type DjSublistReply struct {
	Count    int         `json:"count"`
	DjRadios interface{} `json:"djRadios"`
	Time     int         `json:"time"`
	HasMore  bool        `json:"hasMore"`
	Code     int         `json:"code"`
}

type DjSubscriberReq struct {
	Time  string `form:"time,default=-1"`
	Id    int    `form:"id"`
	Limit int    `form:"limit,default=20"`
	Total bool   `form:"total,default=true"`
}

type DjSubscriberReply struct {
	Subscribers interface{} `json:"subscribers"`
	Time        int         `json:"time"`
	HasMore     bool        `json:"hasMore"`
	Code        int         `json:"code"`
}

type DjTodayPerferedReq struct {
	Page int `form:"page,default=0"`
}

type DjTodayPerferedReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DjToplistReq struct {
	Type   int `form:"type,options=0,1,default=0"`
	Limit  int `form:"limit,default=100"`
	Offset int `form:"offset,default=0"`
}

type DjToplistReply struct {
	UpdateTime string      `json:"updateTime"`
	Toplist    interface{} `json:"toplist"`
	Code       int         `json:"code"`
}

type DjToplistHoursReq struct {
	Limit int `form:"limit,default=100"`
}

type DjToplistHoursReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DjToplistNewcomerReq struct {
	Limit  int `form:"limit,default=100"`
	Offset int `form:"offset,default=0"`
}

type DjToplistNewcomerReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DjToplistPayReq struct {
	Limit int `form:"limit,default=100"`
}

type DjToplistPayReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type DjToplistPopularReq struct {
	Limit int `form:"limit,default=100"`
}

type DjToplistPopularReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
