// Code generated by goctl. DO NOT EDIT.
package types

type UserAccountReq struct {
}

type UserAccountReply struct {
	Code    int         `json:"code"`
	Account interface{} `json:"account"`
	Profile interface{} `json:"profile"`
}
