// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"music/service/dj/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/dj/banner",
				Handler: DjBannerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/category/excludehot",
				Handler: DjCategoryExcludehotHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/category/recommend",
				Handler: DjCategoryRecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/catelist",
				Handler: DjCatelistHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/detail",
				Handler: DjDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/hot",
				Handler: DjHotHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/paygift",
				Handler: DjPaygiftHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/personalize/recommend",
				Handler: DjPersonalizeRecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/program",
				Handler: DjProgramHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/program/detail",
				Handler: DjProgramDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/program/toplist",
				Handler: DjProgramToplistHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/program/toplist/hours",
				Handler: DjProgramToplistHoursHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/radio/hot",
				Handler: DjRadioHotHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/recommend",
				Handler: DjRecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/recommend/type",
				Handler: DjRecommendTypeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/sublist",
				Handler: DjSublistHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/subscriber",
				Handler: DjSubscriberHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/today/perfered",
				Handler: DjTodayPerferedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/toplist",
				Handler: DjToplistHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/toplist/hours",
				Handler: DjToplistHoursHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/toplist/newcomer",
				Handler: DjToplistNewcomerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/toplist/pay",
				Handler: DjToplistPayHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dj/toplist/popular",
				Handler: DjToplistPopularHandler(serverCtx),
			},
		},
	)
}
